
name: aws
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Estado y navegación
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.1

  # HTTP y logging
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^9.2.4

  # Base de datos local y utilidades
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4
  # Deja que flutter_localizations fije intl a 0.20.2; si prefieres, descomenta la siguiente línea:
  # intl: ^0.20.2

  # Escaneo y cámara
  mobile_scanner: ^7.0.1
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
